### ISSUE TITLE
docker run - "exec format error"

### ISSUE THREAD

**Issue by lucaledda** [HotBlackRobotics/docker-ros-base#1]
After having pulled the rpi3 image I tried to run it by using the command:
docker run -t hbrobotics/ros-base:rpi3

What I got is the following error:
standard_init_linux.go:178: exec user process caused "exec format error"

I am using Ubuntu 16.04 LTS on virtual machine. We noticed that the same error is present when using Ubuntu 17.10 on Asus UX430. How can we fix that problem?

Thanks

**Comment by ludusrusso** [comment]
I should have solved! Please pull the image again and test it!

I've tested in on Ubuntu 16.04!

**Comment by lucaledda** [comment]
Now it works!

Thank you very much!
